version: "3"

services:

  storage:
    container_name: storage
    build: main/java/ch/swindiatours/persistance
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: swindia
    ports:
      - 5432:5432
    restart: always

volumes:
  postgres-volume:

