version: "3"

services:

  db:
    container_name: persistance
    build: main/java/ch/swindiatours/persistance
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: swindia
    ports:
      - 5432:5432
    restart: always

  glassfish:
    image: glassfish:latest
    ports:
      - "4848:4848"
      - "8082:8082"
volumes:
  postgres-volume:
  glassfish-volume:

